### ISSUE TITLE
previous dependencies are copied to the next one. 

### ISSUE THREAD

**Issue by elahi123** [lappsgrid-incubator/tcf-converter-prototype#29]
The output of **Brandeis Stanford Dependency Parser** produces wrong dependency structure when input text contains multiple sentences. 

For example: 
1. depstr_1 copies all the previous dependencies ( i.e. all dependencies of depstr_0) and then its own dependencies. This process continues until the end. Therefore, the last dependency structure contains all dependencies of all sentences.
2. depstr_0 and depstr_1 are two different sentences which have different tokens. but we can see that dep_0_0 and dep_1_0 have the same dependencies. Similarly dep_0_1 and dep_1_1.
3. The example file is attached.

[depshorttest.txt](https://github.com/lappsgrid-services/org.lappsgrid.converters.tcf/files/2506554/depshorttest.txt)

{
                        "id": "depstr_0",
                        "start": 0,
                        "end": 23,
                        "@type": "http://vocab.lappsgrid.org/DependencyStructure",
                        "features": {
                            "dependencies": ["dep_0_0", "dep_0_1", "dep_0_2", "dep_0_3", "dep_0_4"]
                        }
                    },
{
                        "id": "dep_0_0",
                        "@type": "http://vocab.lappsgrid.org/Dependency",
                        "label": "ROOT",
                        "features": {
                            "dependent": "v1:t_1"
                        }
                    }, {
                        "id": "dep_0_1",
                        "@type": "http://vocab.lappsgrid.org/Dependency",
                        "label": "nn",
                        "features": {
                            "dependent": "v1:t_3",
                            "governor": "v1:t_4"
                        }
                    }, 

{
                        "id": "depstr_1",
                        "start": 24,
                        "end": 47,
                        "@type": "http://vocab.lappsgrid.org/DependencyStructure",
                        "features": {
                            "dependencies": ["**dep_1_0", "dep_1_1", "dep_1_2", "dep_1_3", "dep_1_4"**, "dep_1_5", "dep_1_6", "dep_1_7", "dep_1_8", "dep_1_9"]
                        }
                    },
{
                        "id": "dep_1_0",
                        "@type": "http://vocab.lappsgrid.org/Dependency",
                        "label": "ROOT",
                        "features": {
                            "dependent": "v1:t_1"
                        }
                    }, {
                        "id": "dep_1_1",
                        "@type": "http://vocab.lappsgrid.org/Dependency",
                        "label": "nn",
                        "features": {
                            "dependent": "v1:t_3",
                            "governor": "v1:t_4"
                        }
                    },

**Comment by keighrim** [comment]
Not sure which version of the Brandeis parser you used, but this is fixed in the latest snapshot, which, I believe, is unlikely to be accessible via a API call. I'll let you know I deploy the new version.

**Comment by elahi123** [comment]
-I think we can see that from attached file. The metadata portion states the version (produce and tool). version.brandeis_eldrad_grid_1:stanfordnlp.dependencyparser_2.0.4
Before the demo in Vassar, I think I moved to latest working version which is tested.
-Ok then please inform me the version that solves the problem.

**Comment by keighrim** [comment]
This looks like an issue in LIF >> TCF conversion. 
Here's a LIF source file and its converted TCF file. 
[brandeis-stanford-2.1.0.txt](https://github.com/lappsgrid-services/org.lappsgrid.converters.tcf/files/2515451/brandeis-stanford-2.1.0.txt)


[tcf-conversion-2.1.0.xml.txt](https://github.com/lappsgrid-services/org.lappsgrid.converters.tcf/files/2515453/tcf-conversion-2.1.0.xml.txt)

By the way, I used brandeis stanford 2.1.0 (which generated "new" named entity annotations and the LIF to TCF converter works fine with it. So let's stick to that version (which I believe was a intermediate version of upgrading to new lapps vocab and lif schema) for the moment.

**Comment by elahi123** [comment]
OK. I will look into it named entity issue and let you know. I think the dependency issue is resolved. I get correct information. The visualisation is also ok.

**Comment by elahi123** [comment]
OK. I will look into the named entity issue. I think the duplicate issue on dependency parse 
 is  gone. It is ok but the  visualisation still does not show completely correct. I will test more dependencies and let you know.

**Comment by elahi123** [comment]
The issue is resolved
